### ISSUE TITLE
Suggestions for icons: OpenTasks, BOINC, Diaspora, Seafile, Keepass2Android, Xabber, G-Authenticator, GeoGebra, Wifi Analyzer, K9Mail, Threema, 

### ISSUE THREAD

**Issue by conrad-heimbold** [1C3/ICEcons#1]
<body>

<p> I am new to github and don't yet know how to make a pull request, and therefore did not make a pull request; but it would be really cool if you could include the following app icons in your repo (most of them are even open source). Unfortunately, you can't see the icons, because they are white on a white background and github does not allow you to change that, but if you open them in another tab of your browser, you can see them, because then the background is not white... </p>

<table style="background-color: grey">
<tr>
<th>app name</th>
<th>application package name</th>
<th>icon</th>
<th>source code</th></tr>
<tr>
<td>OpenTasks</td>
<td>org.dmfs.tasks</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15094867/d8dfd8f2-14b1-11e6-9cb0-0c1c29ba7c52.png" alt=opentasks></td><td><a href="https://github.com/dmfs/opentasks">https://github.com/dmfs/opentasks</a></td>
</tr>
<tr>
<td>BOINC</td>
<td>edu.berkeley.boinc</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15094886/55357f06-14b2-11e6-8cee-25ae73b70565.png" alt=boinc></td>
<td><a href="https://github.com/BOINC/boinc/tree/master/android/BOINC">https://github.com/BOINC/boinc/tree/master/android/BOINC</a></td>
</tr>
<tr>
<td>Diaspora</td>
<td>com.github.dfa.diaspora_android </br> or com.voidcode.diasporawebclient </td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15094902/b0978c40-14b2-11e6-853a-c33a3b97d738.png" alt=diaspora></td>
<td>
<a href="https://github.com/Diaspora-for-Android/diaspora-android">https://github.com/Diaspora-for-Android/diaspora-android</a>
</br>or <a href="https://github.com/voidcode/Diaspora-Webclient">https://github.com/voidcode/Diaspora-Webclient</a></td>
</tr>
<tr>
<td>Seafile</td>
<td>com.seafile.seadroid2</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15094955/42675c30-14b4-11e6-9ab8-cc6c142d8251.png" alt=seafile></td>
<td><a href="https://github.com/haiwen/seadroid">https://github.com/haiwen/seadroid</a></td>
</tr>
<tr>
<td>KeePass2Android</td>
<td>com.keepass2android.keepass2android</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15095106/d880c342-14b8-11e6-9d70-f17c9d9593fb.png" alt=keepass2android></td>
<td><a href="https://keepass2android.codeplex.com/">https://keepass2android.codeplex.com/</a></td>
</tr>
<tr>
<td>Xabber</td>
<td>com.xabber.androiddev</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15095152/71898712-14ba-11e6-8fc9-4acf2593da65.png"></td>
<td><a href="https://github.com/redsolution/xabber-android">https://github.com/redsolution/xabber-android</a></td>
</tr>
<tr>
<td>Google Authenticator</td>
<td>com.google.android.apps.authenticator2</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15095169/02d868b4-14bb-11e6-96d2-1a6b3d63d90f.png" alt="google authenticator"></td>
<td><a href="https://github.com/google/google-authenticator">https://github.com/google/google-authenticator</a></td>
</tr>
<tr>
<td>GeoGebra</td>
<td>org.geogebra.android</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15095220/d437fe64-14bc-11e6-8b22-2565d8768155.png" alt=GeoGebra></td>
<td><a href="https://github.com/geogebra/geogebra">https://github.com/geogebra/geogebra</a></td>
</tr>
<tr>
<td>WiFi Analyzer</td>
<td>com.vrem.wifianalyzer</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15095246/b12454a8-14bd-11e6-9d04-8edf67aef518.png" alt=wifi_analyzer></td>
<td><a href="https://github.com/VREMSoftwareDevelopment/WifiAnalyzer">https://github.com/VREMSoftwareDevelopment/WifiAnalyzer</a></td>
</tr>
<tr>
<td>K9Mail</td>
<td>com.fsck.k9</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15095263/41c30c02-14be-11e6-8dad-efcf249707f5.png" alt=k9mail></td>
<td><a href="https://github.com/k9mail/k-9">https://github.com/k9mail/k-9</a></td>
</tr>
<tr>
<td>Threema</td>
<td>ch.threema.app</td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15095131/a462161e-14b9-11e6-8e8e-71ea6ff16a48.png" alt=threema></td>
<td>not open source, <a href="https://threema.ch/en">company website</a> is here, <a href="https://play.google.com/store/apps/details?id=ch.threema.app">on Google Play</a></td>
</tr>
</table>

</body>
</html>

**Comment by atmtck** [comment]
Thank you for making a contribution, I can't directly include those icons because they do not fit the style of the others, but will remake them and add them to the latest release. Also, since I want all icons in this app to be my original work, opening an issue is a better way to ask for more icons than pulling and then requesting a merge that I would probably have refused, so don't worry about the pull because you did the right thing. Also it's completely ok to request closed source apps, but I will always prioritize open source ones.

**Comment by atmtck** [comment]
Just made a new release, let me know if it has all the requested icons working so I can close the issue

**Comment by conrad-heimbold** [comment]
Thanks for including those icons and all the work needed to be done for making the 3D icons flat! I really like the style of the icons. Just one question: why did you change the icon for keepass2android so completely? I can not re-recognize it that good, although I will probably get used to it. I suppose, making the 3D k9mail icon flat into a 2D one was quite difficult?

**Comment by atmtck** [comment]
I'm glad you like them. As for your questions:
- The reason I simplified the icon for keepass so much is that if I just flattened the original it would look too crowded with details compared with the rest of the icon pack, so, since it represents an android fused with a lock, I just turned it into an android with a keyhole, which looks a bit different but has a similar meaning
- Flattening the K-9 mail icon wasn't really that difficult, I just imagined how the dog would look seen from the front and reused the mail icon from my pack in order to make it look more coherent with the rest, but I'm not completely pleased with the result so I will probably tweak it a bit in the future.
