### ISSUE TITLE
suggestions and requests for icons: (too many too include in the title)

### ISSUE THREAD

**Issue by conrad-heimbold** [1C3/ICEcons#11]
<span>Hello 1C3,</span><br/>
<span>here are some suggestions (the black ones) and requests (the colored ones are taken directly from the source) for icons:</span> 

<table>

<tr><th>app</th><th>licence:</th><th>icon</th><th>package name:</th><th>activity name:</th></tr>
<tr><td>Doodle</td><td>proprietary</td><td><img src="https://cloud.githubusercontent.com/assets/17474312/15562731/277c65e4-2302-11e6-8e97-dfd321728e86.png" height=20px width=20px /></td><td>com.doodle.android</td><td>com.doodle.activites.SplashActivity</td></tr>

<tr><td>DuckDuckGo</td><td>open source (Apache 2)</td><td><img src="https://cloud.githubusercontent.com/assets/17474312/15595860/d443ed36-23c2-11e6-846d-27306d39a725.png" height=20px width=20px/></td><td>com.duckduckgo.mobile.android</td><td>com.duckduckgo.mobile.android.activity.DuckDuckGo</td></tr>

<tr><td>Quizlet</td><td>proprietary</td><td><img src="https://cloud.githubusercontent.com/assets/17474312/15595947/9a3df694-23c3-11e6-8fdd-cc640cc5cbec.png" height=20px width=20px /></td><td>com.quizlet.quizletandroid</td><td>com.quizlet.quizletandroid.activities.RootActivity</td></tr>

<tr><td>Sensor Readout</td><td>open source (Apache 2)</td><td><img src="https://cloud.githubusercontent.com/assets/17474312/15596041/5dd56b78-23c4-11e6-8127-ed237363015e.png" height=20px width=20px /></td><td>de.onyxbits.sensorreadout</td><td>de.onyxbits.sensorreadout.OverviewActivity</td></tr>

<tr><td>QR Plugin for Keepass2Android</td><td>open source (Apache 2)</td><td><img src="https://cloud.githubusercontent.com/assets/17474312/15596102/db0d8ef4-23c4-11e6-86a7-0b041698a8e3.png" height=20px width=20px></td><td>keepass2android.plugin.qr</td><td>keepass2android.plugin.qr.MainActivity</td></tr>

<tr><td>Deutsche Bahn Navigator</td><td>proprietary</td><td><img src="https://cloud.githubusercontent.com/assets/17474312/15596137/364fbc1a-23c5-11e6-936f-587c0371b659.png" height=20px width=20px></td><td>de.hafas.android.db</td><td>de.hafas.main.HafasApp</td></tr>

<tr><td>System App Mover</td><td>open source (Apache 2)</td><td><img src="https://raw.githubusercontent.com/j4velin/SystemAppMover/master/src/main/res/drawable-xhdpi/ic_launcher.png" height=20px width=20px/></td><td>de.j4velin.systemappmover</td><td>de.j4velin.systemappmover.MoverActivity</td></tr>

<tr><td>2048</td><td>open source (MIT)</td><td><img src="https://raw.githubusercontent.com/uberspot/2048-android/master/res/drawable-xxhdpi/ic_launcher.png" height=20px width=20px /></td><td>com.uberspot.a2048</td><td>com.uberspot.a2048.MainActivity</td></tr>

<tr><td>Apps2Org</td><td>open source (GPLv3)</td><td><img src="https://raw.githubusercontent.com/pfalcon/apps2org/master/res/drawable/icon.png" width=20px height=20px /></td><td>com.google.code.apps2org</td><td>com.google.code.appsorganizer.SplashScreenActivity</td></tr>

<tr><td>Birthday Adapter</td><td>open source (GPLv3)</td><td><img src="https://raw.githubusercontent.com/SufficientlySecure/birthday-adapter/master/Birthday-Adapter/src/main/res/mipmap-xxxhdpi/ic_launcher.png" width=20px height=20px /></td><td>org.birthdayadapter</td><td>org.birthdayadapter.ui.BaseActivity</td></tr>

<tr><td>OpenConnect</td><td>open source (GPLv2+)</td><td><img src="https://raw.githubusercontent.com/cernekee/ics-openconnect/master/res/drawable-xxxhdpi/ic_launcher.png" width=20px height=20px/></td><td>app.openconnect</td><td>app.openconnect.MainActivity</td></tr>

<tr><td>OpenMensa</td><td>open source (Apache 2)</td><td><img src="https://raw.githubusercontent.com/domoritz/open-mensa-android/master/res/drawable-xhdpi/ic_launcher.png" width=20px height=20px/></td><td>de.uni_potsdam.hpi.openmensa</td><td>de.uni_potsdam.hpi.openmensa.MainActivity</td></tr>

<tr><td>WebOPAC</td><td>open source (MIT)</td><td><img src="https://raw.githubusercontent.com/opacapp/opacclient/master/img/ic_launcher.png" width=20px height=20px /></td><td>de.geeksfactory.opacclient</td><td>de.geeksfactory.opacclient.frontend.MainActivity</td></tr>
</table>

**Comment by atmtck** [comment]
All icons should be in the new release, I fixed the forkhub typo too

**Comment by conrad-heimbold** [comment]
I made a typo again, I forgot an "i" in "activities": the activity name for doodle should be "com.doodle.activities.SplashActivity" and not
