### ISSUE TITLE
Suggestions for icons: AnkiDroid; Das Erste; chefkoch

### ISSUE THREAD

**Issue by conrad-heimbold** [1C3/ICEcons#3]
<p>Hello, I've got some suggestions for app icons again, this time mostly closed-source ones, that are quite much known.  </br>
I derived all of these icons by myself from the mentioned icon origin. </p>

<table style="width: 1500px">
<tr>
<th>name:</th>
<th>app package name:</th>
<th>activity name:</th>
<th>licence:</th>
<th>website:</th>
<th>icon</th>
<th>icon origin</th>
<th><nobr>copyright notes:</nobr></th>
</tr>
<tr>
<td>AnkiDroid</td>
<td>com.ichi2.anki</td>
<td>com.ichi2.anki.<br/>IntentHandler</td>
<td>GPL</td>
<td><ul><li><a href="https://github.com/ankidroid/Anki-Android">github repository</a></li>
<li><a href="https://play.google.com/store/apps/details?id=com.ichi2.anki">app on google play</a></li></td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15195179/f512b086-17c6-11e6-82a7-d32756e906fb.png" alt=AnkiDroid></td>
<td><a href="https://groups.google.com/forum/#!searchin/anki-android/icon/anki-android/yUJQWSEWfNQ/2vWc2wxsCQAJ">Google Group</a></td>
<td><small>creator of original icon: <a href="https://plus.google.com/109593746000218525778">Norbert Szulc</a></small></td>
</tr>
<tr>
<td>Das Erste*</td>
<td>com.daserste.<br/>daserste</td>
<td>com.daserste.<br/>daserste.DasErste</td>
<td>proprietary</td>
<td><ul>
<li><a href="http://www.daserste.de/">organisation website</a></li>
<li><a href="https://play.google.com/store/apps/details?id=com.daserste.daserste">app on google play</a></li></ul></td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15196391/48eac180-17cc-11e6-8ec8-6a786dbbf89c.png" alt=Das_Erste></td>
<td><a href="https://commons.wikimedia.org/wiki/File:Das_Erste_2014.svg">Wikimedia</a></td>
<td>not enough originality in icon for copyright => in public domain; but trademark of "Das Erste". </td>
</tr>
<tr>
<td>chefkoch</td>
<td>de.pixelhouse</td>
<td>de.pixelhouse.<br/>chefkoch.HomeActivity_ (_ is intended!)</td>
<td>proprietary</td>
<td><ul>
<li><a href="http://www.chefkoch.de">company website</a></li>
<li><a href="https://play.google.com/store/apps/details?id=de.pixelhouse">app on google play</a></li></ul></td>
<td><img src="https://cloud.githubusercontent.com/assets/17474312/15200131/6c14109a-17e4-11e6-9a6d-cfe5a18cc185.png"></td>
<td><a href="https://img.chefkoch-cdn.de/img/ck.de/ck-logo-de.png">company website</a></td>
<td>company does not explicitly forbid you to alter their trademark icon and use it for their services.</td>
</tr>
</table>

<p>*) "Das Erste" is the principal publicly owned television channel in Germany. </p>

<p>There were a couple a more icons for proprietary apps that I would have loved to include in this list, but the companies behind those apps forbid you to change their logos and redistribute them; even if only used for their products. I did not want to commit a copyright infringement. </p>

**Comment by conrad-heimbold** [comment]
I think you could directly include the icon for "Das Erste" in the app, because it does fit to the style of the other icons and it is in public domain, right? The only limitation with "Das Erste"-icon: it should only be used for the app "Das Erste", as it might be a trademark.

**Comment by atmtck** [comment]
Yes I think I will include das erste directly if I can find a vectorized drawable. I keep all icons in svg format so when higher density buckets get added to android i can just automatically create pngs in whatever resolutions are needed using scripts. Otherwise I will redraw that one too, it doesn't seem like much work anyway.

**Comment by atmtck** [comment]
I don't have the playstore and I can't find another way to obtain apks for das erste and chefkoch, so I need you to find the componentinfo trough something like turtl https://f-droid.org/repository/browse/?fdfilter=turtl&fdid=org.xphnx.iconsubmit and post them here for me.

**Comment by conrad-heimbold** [comment]
Hello 1C3, I added the necessary details in the table above. 
BTW: I used <a href="https://f-droid.org/repository/browse/?fdid=de.szalkowski.activitylauncher">Activity Launcher</a> instead of <a href="https://f-droid.org/repository/browse/?fdid=org.xphnx.iconsubmit">turtl</a> to get the necessary activity details.

**Comment by atmtck** [comment]
Release 2.5 is here, should also be on fdroid tomorrow, check it out and if everything is ok close the issue.
