### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by baconicsynergy** [1C3/ICEcons#4]
This is my favorite icon pack EVER. I would love icons for Amaze, Chromium, Etar, Forkhub, IceCat, Kore, Leafpic, OpenVPN, Privacy Browser, Radiodroid, Red Moon, Slide, Sound Recorder, and the stock android phone dialer. Keep up the good work

**Comment by conrad-heimbold** [comment]
As far as I know, an icon for Sound Recorder and the stock Android Dialer should already be included. Were those icons not set properly? I think, you can also select icons for apps manually...

**Comment by conrad-heimbold** [comment]
Concerning chromium: Making a chromium icon that is different from the chrome one will definitely destroy re-recognition, because the only difference between the official icon for chrome and chromium is the color, which obviously gets lost with a white icon. May I suggest you to just use the chrome one?

**Comment by conrad-heimbold** [comment]
Concerning chromium: Maybe you can also mix the symbol for open source software (here comes the white icon on a white background....)<br/> <img src="https://cloud.githubusercontent.com/assets/17474312/15226685/0994f66e-1884-11e6-8fe1-d2c116b6c012.png" alt=open_source width=100px background-color=grey> <br/>with the original chrome one?

**Comment by atmtck** [comment]
@baconicsynergy it's nice to hear you like it, I will be busy over the weekend but I'll try to include the missing icons as soon as I can.
The reason sound recorder and dialer do not work is that they can have different package names depending on the phone and I only added the ones on mine. To be able to add yours you would have to tell me their package name and their launcher activity name, a good way to find out what those are is to use the icon request utility in https://f-droid.org/repository/browse/?fdfilter=blue+minimal&fdid=de.baumann.thema
In the meantime you can either use nova launcher, where they should be set correctly anyway thanks to nova being able to recognize stock android apps by itself, or set them manually through whatever launcher you use.
Chromium is another app which is problematic because there are many different builds made by different developers which may have different package names, so same as above you can either set the icon manually or find out package and launcher activity names and tell me here.
@conrad-heimbold i don't think chrome and chromium using the same icon constitutes a problem because it doesn't make much sense to have both installed on the same phone, so there aren't going to be many situations where they can be mixed up anyway, maybe some day I will try to differentiate them but missing icons have the priority.

**Comment by baconicsynergy** [comment]
Perhaps the colors could be inverted for Chromium?

**Comment by baconicsynergy** [comment]
I should have specified, the Sound Recorder app I mentioned isn't stock, it can be found in F-Droid - https://github.com/dkim0419/SoundRecorder

**Comment by baconicsynergy** [comment]
Here is the chromium (from getChromium, fdroid) and stock phone app info for galaxy s6 android 6:

Chromium
org.chromium.chrome/
com.google.android.apps.chrome.Main

Phone
com.android.contacts/com.android.dialer.DialtactsActivity

**Comment by baconicsynergy** [comment]
I used Turtl - https://github.com/turtl to find info for missing icons so I think it deserves one too :)

**Comment by conrad-heimbold** [comment]
<p>Here are the package names for the requested app icons. I hope I can help 1C3 with this!</p>

<p>On the right, you can also see the original icons</p>

<table>
<tr><th>app:</th><th>app package name:</th><th>activity name:</th><th>png icon as inspiration for @1C3 :</th></tr>
<tr><td>Amaze</td><td>com.amaze.filemanager</td><td><small>com.amaze.activities.<br/>MainActivity</small></td><td><a href="https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/res/mipmap-xxxhdpi/ic_launcher.png">amaze icon</a> made by @vishal0071</td></tr>
<tr><td>Chromium</td><td>org.chromium.chrome</td><td>com.google.android.apps.<br/>chrome.Main</td><td><a href="https://www.chromium.org/_/rsrc/1438879449147/config/customLogo.gif?revision=3">logo on chromium website</a></td></tr>
<tr><td>Etar</td><td>ws.xsoh.etar</td><td>com.android.calendar.<br/>AllInOneActivity</td><td><a href="https://github.com/xsoh/Etar-Calendar/blob/master/res/mipmap-xxxhdpi/ic_launcher.png">etar icon</a> made by @xsoh (Suhail Alkowaileet)</td></tr>
<tr><td>Forkhub</td><td>jp.forkhub</td><td>jp.forkhub.ui.<br/>user.HomeActivity</td><td><a href="https://github.com/jonan/ForkHub/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png">Forkhub icon</a> made by @jonan (Jon Ander Peñalba)</td></tr>
<tr><td>Icecat</td><td>org.gnu.icecat</td><td>org.gnu.icecat.<br/>App</td><td><a href="https://www.gnu.org/software/gnuzilla/icecat.png">gnu icecat icon</a></td></tr>
<tr><td>Kore</td><td>org.xbmc.kore</td><td>org.xbmc.kore.<br/>ui.RemoteActivity</td><td><a href="https://github.com/xbmc/Kore/blob/master/app/src/main/res/drawable-xxhdpi/ic_launcher.png">Kore icon</a> made by @SyncedSynapse (Synced Synapse)</td></tr>
<tr><td>Leafpic</td><td>com.horaapps.leafpic</td><td>com.horaapps.leafpic.<br/>MainActivity</td><td><a href="https://github.com/HoraApps/LeafPic/blob/master/app/src/main/res/mipmap-xxhdpi/ic_launcher.png">leafpic icon</a> made by @Mow3l (Gilbert Ndresaj)</td></tr>
<tr><td>OpenVPN</td><td>de.blinkt.openvpn</td><td>de.blinkt.openvpn.<br/>activities.MainActivity</td><td><a href="https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/res/drawable-xxhdpi/icon.png">OpenVPN icon</a> made by @schwabe (Arne Schwabe)</td></tr>
<tr><td>Privacy Browser</td><td>com.stoutner<by>.privacybrowser.<br/>standard</td><td>com.stoutner.privacybrowser.<br/>standard.MainWebViewActivity</td><td><a href="https://git.stoutner.com/?p=PrivacyBrowser.git;a=blob;f=app/src/main/res/mipmap-xxxhdpi/privacy_browser.png;h=417fc20f4e4db04ff52d286a90a319ea54ff8a40;hb=HEAD">privacy browser icon</a> made by Soren Stoutner</td></tr>
<tr><td>Radiodroid</td><td>net.programmierecke.<br/>radiodroid2</td><td>net.programmierecke.<br/>radiodroid2.ActivityMain</td><td><a href="https://github.com/segler-alex/RadioDroid/blob/master/app/src/main/res/drawable-xxxhdpi/ic_launcher.png"> Radiodroid icon </a>made by @segler-alex</td></tr>
<tr><td>Red Moon</td><td>com.jmstudios.redmoon</td><td>com.jmstudios.redmoon.<br/>activity.ShadesActivity</td><td><a href="https://github.com/raatmarien/red-moon/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png">red moon icon </a>made by @raatmarien (Marien Raat)</td></tr>
<tr><td>Slide</td><td>trikita.slide *</td><td>trikita.slide.<br/>ui.MainActivity</td><td><a href="https://github.com/trikita/slide/blob/master/src/main/res/mipmap-xxxhdpi/ic_launcher.png">slide icon </a>made by @krugloid and @zserge (Serge Zaitsev)</td></tr>
<tr><td>Slide</td><td>me.ccrama.redditslide  @*</td><td>me.ccrama.redditslide.<br/>Activities.Slide</td><td><a href="https://github.com/ccrama/Slide/blob/master/app/src/main/res/mipmap-xxhdpi/ic_launcher.png">slide icon </a>made by @ccrama and @GermainZ (Germain Z.)</td></tr>
<tr><td>Sound Recorder</td><td>com.danielkim.soundrecorder</td><td>com.danielkim.soundrecorder.<br/>activities.MainActivity</td><td><a href="https://github.com/dkim0419/SoundRecorder/blob/master/app/src/main/res/drawable-xxxhdpi/ic_launcher.png">sound recorder icon</a> made by @dkim0419 (Daniel Kim Yehun) and @createme</td></tr>
<tr><td>Android Dialer</td><td>com.android.dialer</td><td>com.android.dialer.</td><td>no icon found</td></tr>
<tr><td>Android Contacts</td><td>com.android.contacts</td><td>com.android.contacts.<br/>activities.ContactsFrontDoor</td><td>no icon found</td></tr>
<tr><td>Turtl</td><td>org.xphnx.iconsubmit</td><td>org.xphnx.iconsubmit.<br/>MainActivity</td><td><a href="https://gitlab.com/xphnx/icon-request-tool/blob/master/app/src/main/res/drawable/ic_launcher.png">turtle icon </a>made by <a href="mailto:xphnx@protonmail.ch">Xphnx</a> (write E-mail)</td></tr>
</table>

*) Which "Slide" do you mean, @baconicsynergy ? The one for presentations or the one for reddit?

**Comment by baconicsynergy** [comment]
@conrad-heimbold i meant the one for reddit but the presentation app is very useful, so why not both?

**Comment by atmtck** [comment]
Release 2.5 is here, should also be on fdroid tomorrow, check it out and if everything is ok close the issue.

**Comment by baconicsynergy** [comment]
Nice! I'll try to package it early for myself because I'm impatient

**Comment by conrad-heimbold** [comment]
The icon for Amaze has not been set in my case, all other icons are working however (after re-installing the app). I think that's because I made a typo: the activity name should be: 

com.amaze.filemanager.activities.MainActivity

and NOT

com.amaze.activities.MainActivity

**Comment by atmtck** [comment]
amaze typo has been fixed
