### ISSUE TITLE
Typos I made for amaze and forkhub

### ISSUE THREAD

**Issue by conrad-heimbold** [1C3/ICEcons#8]
Hi 1C3, I made a typo when telling you the details for some apps: 

<ul>
<li>the activity name for amaze should be `com.amaze.filemanager.activities.MainActivity`
and NOT `com.amaze.activities.MainActivity`. </li>
<li>the activity name for forkhub should be
`com.github.mobile.ui.user.HomeActivity` 
and NOT `jp.forkhub.ui.user.HomeActivity`.</li>
</ul>

Could you update those details? Thanks. 
For the next time, it is probably better if I use Turtle...

**Comment by atmtck** [comment]
Oops, I just published a release with the correct amaze activity name, so that should be fixed, forkhub will have to wait for the next release I guess.
